### PR TITLE
feat: Automatically whitelist content:// and cdvfile:// files (CB-9133)

### PR DESCRIPTION
**Pull request by agamemnus**
Reposting from closed pull request for clarity. Still haven't reviewed the official documentation for Chromium whitelisting, but this is a start.

### CODE REVIEW

**Comment by csantanapr** [comment]
Can you open a JIRA for this change, and the reasoning behind?

What is content:// for?

Why do you think this have to be added by default instead of having developer explicit added them to via config.xml or plugin?

We want whitelist to be lock/secure by default, and developer to open only what's required, not every developer needs all these defaults.

cc @infil00p

**Comment by agamemnus** [comment]
Wew lad. I think I just had a heart attack...

I don't really know where to begin to answer your question. The whitelist addition borked years of Cordova functionality.

https://issues.apache.org/jira/browse/CB-9133

**Comment by infil00p** [comment]
@agamemnus Can you rebase these down to a single commit and make the commit describe what the commit actually does?  The whitelist is meant to shut down these URIs, but I do think that it's somewhat overkill.

**Comment by agamemnus** [comment]
Ok. Will do so ASAP.

**Comment by agamemnus** [comment]
Oh sorry. Yeah, everything keeps changing so rapidly that I can't even keep up with my single major plugin.

Put this on my todo for the weekend.

**Comment by agamemnus** [comment]
D:

**Comment by janpio** [comment]
Ci: Let there be tests.

**Comment by PieterVanPoyer** [comment]
My excuses for not addressing this issue earlier. Thanks for your effort.
But, the plugin is being deprecated, so this PR will not be merged in.

**Comment by agamemnus** [comment]
What's in its place?

**Comment by PieterVanPoyer** [comment]
The plugin will be renamed to AllowList and will be embedded in the cordova-android core repo. @see https://github.com/apache/cordova-android/pull/1138/files

**Comment by agamemnus** [comment]
...

It's ... Just a rename ...?

Is it fixed in the renamed plugin?

**Comment by agamemnus** [comment]
Or......? Pls respond.

**Comment by PieterVanPoyer** [comment]
Hey agememnus

It is indeed a rename and a replacement of the plugin (from plugin to `cordova-android` repo).
The issue is as far as I know not solved in the `cordova-android` repo.

There are currently also some issues with the `cdvfile` protocol in the `cordova-android` repo.
Maybe we can pick this up in september. 

I'll be happy to make an issue with this request in september.

Kind regards

**Pull request closed without merging**
