### PR TITLE
CB-10624 remove error message from whitelist.js, which leaves it empty

### PR DESCRIPTION
**Pull request by eymorale**

### CODE REVIEW

**Comment by eymorale** [comment]
@infil00p and @csantanapr can you take a look at this and see if you have any problems with it?

**Comment by csantanapr** [comment]
I agree we should remove the file all together is not required for functionality that the plugin offers.

@infil00p Are you OK with the removal of the js file?

@infil00p the error message is anorying and confusing to developers in the console.
CSP is not required for the Whitelist code to work. I think we should also move the CSP info from the README to the Security Guide in the docs, it gives the false impresion that the cordova plugin is parsing the CSP tag and processing and doing something with it.

**Comment by jcesarmobile** [comment]
+1
In addition, it's not consistent with other platforms. Android is the only one that shows this warning.
We should encorage users to use the CSP, but not sure if showing a warning is the best way of doing it.
Most answers on stackoverflow questiongs about this warning just tell how to use an empty CSP so it stops complaining or use CSP that allows everything.

**Comment by csantanapr** [comment]
Thanks @jcesarmobile for commenting we wanted someone to review it before we took it out.

@eymorale looks like it's OK to go ahead and remove then.

**Pull request closed without merging**
