### PR TITLE
Automatically whitelist content:// and cdvfile:// files.

### PR DESCRIPTION
**Pull request by agamemnus**
Looks like this one works...?

### CODE REVIEW

**Comment by nikhilkh** [comment]
Thanks, @agamemnus for the contribution! Do you have an Apache CLA signed? If not, please sign one http://www.apache.org/licenses/icla.txt and send it to secretary@apache.org. Do you have a JIRA for this issue you are trying to fix explaining why it needs to be fixed? If not, it will help to file one here: https://issues.apache.org/jira/

**Comment by agamemnus** [comment]
Yes to both questions.

https://issues.apache.org/jira/browse/CB-9133

P.S.: If you could take a look at https://issues.apache.org/jira/browse/CB-9132 that would be nice too.

**Comment by nikhilkh** [comment]
The issue you describe in the JIRA has to do with updates to the CSP and not the whitelist itself.

**Comment by agamemnus** [comment]
Well, there are really 2 issues, sort of.

First of all, cdvfile:// and content:// should be automatically whitelisted. That's what this patch is about.

Secondly, assuming for some reason they shouldn't be automatically whitelisted (but they should), the CSP meta tag example in the readme for this plugin is not expansive enough.

**Comment by nikhilkh** [comment]
I'm somewhat new to this area. What is cdvfile and content protocol used for? Does Android actually, support navigating to either. Why should one use cdvfile over file? I will follow up and document some of these aspects if you can help me understand.

**Comment by agamemnus** [comment]
``cdvfile://`` is a protocol used in Cordova for accessing saved files: https://github.com/apache/cordova-plugin-file.

Regarding ``content://``, a little back-story which should help explain. Google Play has a 50 megabyte apk size upload limit. To go beyond that it uses an expansion file system which allows up to (I think) 2 gigabytes of extra storage. The expansion files are typically downloaded to and stored in ``Phone/Android/obb`` as zip files with 0 compression ("STORE"). To access the files Google recommends using a content provider (http://developer.android.com/guide/topics/providers/content-providers.html). (A content provider is used for a few more things, as well...)

I made a comprehensive plugin for using these expansion files here: https://github.com/agamemnus/cordova-plugin-xapkreader/. It links to and makes use of 2 Android libraries made by Google called ``play_apk_expansion`` and ``play_licensing``. A number of people wanted to use Cordova 5, but the plugin doesn't work with 5 because ant support is not supported or broken.

Unfortunately, Gradle support is somewhat broken as well as I describe in https://issues.apache.org/jira/browse/CB-9132.

Even going past the Gradle issues, the whitelist requirement in Cordova 5 means that by default ``content://`` files (the method used to access files in the zip file) are not usable. There are two fixes to this -- patching the whitelist plugin, or adding content:// in the CSP tag.

P.S.: Even with this whitelist plugin patch, I am having issues loading JPG files (but not other types of files) using the ``content://`` protocol (my Chrome debugger claims that ``content://`` protocol is unrecognized), but this may be a Chromium or Crosswalk issue.

**Comment by stevengill** [comment]
This looks good to me. I'll merge it in

**Comment by agamemnus** [comment]
Actually, hold on a second. The change is not quite what the title says. It only automatically whitelists ``content://``, ``cdvfile://``, and ``file://`` for ``allowedNavigations`` if there is a ``*`` origin. What do you think of adding those regardless of the origin?

**Comment by agamemnus** [comment]
(And to be honest, I am fuzzy about what ``allowedNavigations``, ``allowedRequests``, and ``allowedIntents`` exactly mean.)

**Comment by stevengill** [comment]
Argh, Just merged it in haha. I am going to revert it so we have more time to test. Looks like it is causing problems. 

I'd say we stick with keeping it in the loop for now.

I am not super familiar with this plugin. It looks like `allowedNavigations == null` is for giving default access to `file` and `data`. I could see content fitting in there. Don't think we need cdvfile:// unless removing it breaks the file plugin for you.

**Comment by stevengill** [comment]
Reverted it. Hopefully this PR opens agian

**Comment by stevengill** [comment]
This is a pretty big problem IMO. File plugin not working. I am going to test it to see if I can reproduce the issues. A better solution would be if the file plugin added an exception to config.xml when getting installed. Doesn't seem to be doing that right now.

**Comment by agamemnus** [comment]
It is still closed. You have to re-open it manually. (button below comment textbox)

My changes did fix the issue for me, but only because I had the origin at *.

I will read more about whitelist stuff myself and see where the best place is to put it.

**Comment by stevengill** [comment]
I think only you or apache infra people can re-open it.

**Comment by stevengill** [comment]
Any chance you can give me some steps to reproduce it?

**Comment by agamemnus** [comment]
I can't re-open it. Reproduce steps would be to use any Google Expansion File plugin (like mine here, and see these steps to update to Cordova 5: https://github.com/agamemnus/cordova-plugin-xapkreader/issues/22) or use file-transfer plugin to try to add files I suppose.

**Comment by stevengill** [comment]
Sweet! Thanks. I'll take a look tonight/tomorrow and see if we can figure this out. Let me know if you come up with any findings. We may have to open a new PR :(

**Comment by agamemnus** [comment]
Can you find out why this was made mandatory in the first place? Maybe it really shouldn't be.

**Comment by stevengill** [comment]
Why the whitelist plugin was made mandatory?

**Comment by nikhilkh** [comment]
Whitelist plugin is mandatory to be able to connect to internet in the Android platform. By default, the Android 4.0 platform cannot connect to the internet.

**Comment by agamemnus** [comment]
But the Cordova Android 3 is not like that. Why the difference?

**Comment by stevengill** [comment]
Security! 

I do think it is unfortunate that *data and *file aren't on by default without the whitelist plugin.

**Comment by agamemnus** [comment]
Well, in a rush to engineer false sense of security, *someone* messed up big time.

Don't forget ``cdvfile://`` and ``content://``...

**Comment by nikhilkh** [comment]
@agamemnus Wondering if you want to create a new PR for support for cdvfile:// and content:// ?

**Comment by agamemnus** [comment]
Ok, I'll do that...

**Comment by micky2be** [comment]
Would love to see that PR getting in

**Comment by agamemnus** [comment]
Today!

**Comment by agamemnus** [comment]
Reposted. https://github.com/apache/cordova-plugin-whitelist/pull/9

**Pull request closed without merging**
